# Generated by Django 5.0.6 on 2025-01-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_useraccount_deposite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='deposite',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
