# Generated by Django 5.0.6 on 2025-01-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AllBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('borrwing_price', models.IntegerField()),
                ('review', models.CharField(blank=True, max_length=300, null=True)),
                ('Category', models.ManyToManyField(to='books.category')),
            ],
        ),
    ]
