# Generated by Django 5.0.6 on 2025-01-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allbooks',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='books/uploads'),
        ),
    ]
