# Generated by Django 5.0.6 on 2025-01-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_allbooks_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allbooks',
            name='image',
            field=models.ImageField(upload_to='books/uploads'),
        ),
    ]
