# Generated by Django 5.0.6 on 2025-01-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_allbooks_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allbooks',
            name='borrwing_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
