# Generated by Django 5.0.6 on 2025-01-21 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_allbooks_borrwing_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allbooks',
            name='review',
        ),
    ]
