# Generated by Django 5.0.6 on 2025-01-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertranscations',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usertranscations',
            name='transaction_type',
            field=models.CharField(max_length=15),
        ),
    ]
