# Generated by Django 5.0.6 on 2025-01-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_usertranscations_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertranscations',
            name='paid_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
